# Generated by Django 3.1.13 on 2021-09-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReportEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.CharField(max_length=100)),
                ('leave_reason', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.employee')),
            ],
            options={
                'verbose_name': 'LeaveReportEmployee',
                'verbose_name_plural': 'LeaveReportEmployees',
            },
        ),
    ]
