# Generated by Django 4.0.6 on 2022-10-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.employee')),
            ],
            options={
                'verbose_name': 'Notification Employee',
                'verbose_name_plural': 'Notification Employees',
            },
        ),
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.admin')),
            ],
            options={
                'verbose_name': 'Notification Admin',
                'verbose_name_plural': 'Notification Admins',
            },
        ),
        migrations.CreateModel(
            name='LeaveReportEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.TextField()),
                ('leave_start', models.DateTimeField()),
                ('leave_end', models.DateTimeField()),
                ('total_duration_days', models.CharField(blank=True, max_length=100, null=True)),
                ('total_days_left', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_comment', models.CharField(blank=True, max_length=255)),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.employee')),
            ],
            options={
                'verbose_name': 'Leave Report Employee',
                'verbose_name_plural': 'Leave Report Employees',
            },
        ),
        migrations.CreateModel(
            name='LeaveReportAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.CharField(max_length=100)),
                ('leave_reason', models.TextField()),
                ('leave_start', models.DateTimeField()),
                ('leave_end', models.DateTimeField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.admin')),
            ],
            options={
                'verbose_name': 'Leave Report Admin',
                'verbose_name_plural': 'Leave Report Admins',
            },
        ),
        migrations.CreateModel(
            name='FeedBackEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.employee')),
            ],
            options={
                'verbose_name': 'Feed Back Employee',
                'verbose_name_plural': 'Feed Back Employees',
            },
        ),
        migrations.CreateModel(
            name='FeedBackAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.admin')),
            ],
            options={
                'verbose_name': 'Feed Back Admin',
                'verbose_name_plural': 'Feed Back Admins',
            },
        ),
    ]
