# Generated by Django 4.0.6 on 2022-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
