# Generated by Django 3.1.13 on 2021-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
