# Generated by Django 3.1.13 on 2021-09-06 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
        ('leave', '0002_auto_20210906_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavereportemployee',
            options={'verbose_name': 'Leave Report Employee', 'verbose_name_plural': 'Leave Report Employees'},
        ),
        migrations.CreateModel(
            name='FeedBackEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managements.employee')),
            ],
            options={
                'verbose_name': 'Feed Back Employee',
                'verbose_name_plural': 'Feed Back Employees',
            },
        ),
    ]
