# Generated by Django 4.0.6 on 2022-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavereportemployee_is_on_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportemployee',
            name='is_requesting',
            field=models.BooleanField(default=True),
        ),
    ]
