# Generated by Django 3.1.13 on 2021-09-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210906_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackemployee',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
