# Generated by Django 3.1.13 on 2021-08-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ('-date_review',), 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
        migrations.AlterModelOptions(
            name='mailmessage',
            options={'verbose_name': 'Mail Message', 'verbose_name_plural': 'Mail Messages'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
