# Generated by Django 4.0.6 on 2022-10-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('definations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Deduction Attribute',
                'verbose_name_plural': 'Deduction Attributes',
            },
        ),
        migrations.CreateModel(
            name='SalaryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('definations', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Salary Attribute',
                'verbose_name_plural': 'Salary Attributes',
            },
        ),
        migrations.CreateModel(
            name='SetSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.PositiveIntegerField()),
                ('hourly_pay_rate', models.PositiveIntegerField()),
                ('overtime_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('overtime_multiplier', models.FloatField(blank=True, null=True)),
                ('annual_gross_pay', models.PositiveIntegerField(blank=True, null=True)),
                ('addcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.addcategory')),
            ],
            options={
                'verbose_name': 'Set Salary',
                'verbose_name_plural': 'Set Salaries',
            },
        ),
        migrations.CreateModel(
            name='SalaryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('salary_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryattributevaluess', to='set_salary.salaryattribute')),
            ],
            options={
                'verbose_name': 'Salary Attribute Value',
                'verbose_name_plural': 'Salary Attribute Values',
            },
        ),
        migrations.CreateModel(
            name='DeductionAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.PositiveIntegerField()),
                ('deduction_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='set_salary.deductionattribute')),
            ],
            options={
                'verbose_name': 'Deduction Attribute Value',
                'verbose_name_plural': 'Deduction Attribute Values',
            },
        ),
    ]
