# Generated by Django 4.0.6 on 2022-10-03 11:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionattributevalue',
            name='attribute_value',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='salaryattributevalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
