# Generated by Django 4.0.6 on 2022-10-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('set_salary', '0002_alter_deductionattributevalue_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductionattribute',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directors.director'),
        ),
        migrations.AddField(
            model_name='deductionattributevalue',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directors.director'),
        ),
        migrations.AddField(
            model_name='salaryattribute',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directors.director'),
        ),
        migrations.AddField(
            model_name='salaryattributevalue',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directors.director'),
        ),
    ]
