# Generated by Django 4.0.6 on 2022-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('set_salary', '0003_deductionattribute_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryattribute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='salaryattribute',
            unique_together={('director', 'name')},
        ),
    ]
