# Generated by Django 4.0.6 on 2022-10-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('set_salary', '0004_alter_salaryattribute_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salaryattribute',
            name='director',
        ),
        migrations.CreateModel(
            name='PaymentAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: Payment attribute could be that one of Earnings or Deductions', max_length=255)),
                ('definations', models.CharField(max_length=255)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directors.director')),
            ],
            options={
                'verbose_name': 'Payment Attribute',
                'verbose_name_plural': 'Payment Attributes',
                'unique_together': {('director', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='deductionattributevalue',
            name='deduction_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='set_salary.paymentattribute'),
        ),
        migrations.AlterField(
            model_name='salaryattributevalue',
            name='salary_attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryattributevaluess', to='set_salary.paymentattribute'),
        ),
        migrations.DeleteModel(
            name='DeductionAttribute',
        ),
        migrations.DeleteModel(
            name='SalaryAttribute',
        ),
    ]
