# Generated by Django 3.1.13 on 2021-08-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=255)),
                ('sort_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'BankDetail',
                'verbose_name_plural': 'BankDetails',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dob_verify', models.BooleanField(default=False)),
                ('parmanent_home_address', models.CharField(max_length=200)),
                ('parmanent_address_verify', models.BooleanField(default=False)),
                ('contact_address', models.CharField(max_length=255)),
                ('contact_verify', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=100)),
                ('phone_number_2', models.CharField(max_length=100)),
                ('pension_house', models.CharField(max_length=200)),
                ('pension_number', models.CharField(max_length=200)),
                ('PAYEE_ID', models.CharField(max_length=200)),
                ('NHF_ID', models.CharField(max_length=200)),
                ('employment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PersonalInfo',
                'verbose_name_plural': 'PersonalInfos',
            },
        ),
    ]
