# Generated by Django 4.0.6 on 2022-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('bvn', models.CharField(max_length=255)),
                ('sort_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=200)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('date_current', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=200)),
                ('degree_authenticate', models.IntegerField(default=0)),
                ('course', models.CharField(max_length=200)),
                ('nysc_current', models.BooleanField(default=False)),
                ('nysc_ongoing', models.BooleanField(default=False)),
                ('nysc_authenticate', models.IntegerField(default=0)),
                ('members_body', models.CharField(max_length=200)),
                ('membership_number', models.CharField(max_length=100)),
                ('membership_class', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('file1', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('file2', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('file3', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FileUpload',
                'verbose_name_plural': 'File Uploads',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dob_verify', models.IntegerField(default=0)),
                ('parmanent_home_address', models.CharField(max_length=200)),
                ('parmanent_address_verify', models.IntegerField(default=0)),
                ('contact_address', models.CharField(max_length=255)),
                ('contact_verify', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=100)),
                ('phone_number_2', models.CharField(max_length=100)),
                ('pension_house', models.CharField(max_length=200)),
                ('pension_number', models.CharField(max_length=200)),
                ('PAYEE_ID', models.CharField(max_length=200)),
                ('NHF_ID', models.CharField(max_length=200)),
                ('employment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Infos',
            },
        ),
    ]
