# Generated by Django 3.1.13 on 2021-08-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetail',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'BankDetails'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Info', 'verbose_name_plural': 'PersonalInfos'},
        ),
    ]
