# Generated by Django 3.1.13 on 2021-08-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidentials', '0002_auto_20210810_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(editable=False)),
                ('full_name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=200)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('date_current', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=200)),
                ('degree_authenticate', models.BooleanField(default=False)),
                ('degree_attach', models.FileField(upload_to='confidentials')),
                ('course', models.CharField(max_length=200)),
                ('nysc_current', models.BooleanField(default=False)),
                ('nysc_ongoing', models.BooleanField(default=False)),
                ('nysc_authenticate', models.BooleanField(default=False)),
                ('nysc_attach', models.FileField(upload_to='confidentials')),
                ('members_body', models.CharField(max_length=200)),
                ('membership_number', models.CharField(max_length=100)),
                ('membership_class', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='dob_attach',
            field=models.FileField(blank=True, null=True, upload_to='confidentials'),
        ),
    ]
