# Generated by Django 3.1.13 on 2021-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidentials', '0003_auto_20210822_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetail',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Info', 'verbose_name_plural': 'Personal Infos'},
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='employment_date',
            field=models.DateTimeField(),
        ),
    ]
