# Generated by Django 3.1.13 on 2021-08-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail_file',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='video_file',
            new_name='video',
        ),
    ]
