# Generated by Django 3.1.13 on 2021-09-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210916_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='media/'),
        ),
    ]
