# Generated by Django 3.1.13 on 2021-09-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addcategoryforemployee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='addcategoryforemployee',
            name='category',
        ),
        migrations.AlterField(
            model_name='addcategoryforemployee',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.grade'),
        ),
        migrations.AlterField(
            model_name='addcategoryforemployee',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.level'),
        ),
        migrations.AlterField(
            model_name='addcategoryforemployee',
            name='steps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.step'),
        ),
    ]
