# Generated by Django 3.1.13 on 2022-05-10 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='employeecreation')),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bulk Creation',
                'verbose_name_plural': 'Bulk Creations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_unique_id', models.CharField(blank=True, max_length=6)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('fcm_token', models.TextField(blank=True, default='', null=True)),
                ('date_employed', models.DateTimeField(auto_now_add=True, verbose_name='Date Employed')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('profile_pic', models.FileField(blank=True, default='avatar.png', null=True, upload_to='media/')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directors.director')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unique_id', models.CharField(blank=True, max_length=6)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dapartment/Units')),
                ('fcm_token', models.TextField(blank=True, default='', null=True)),
                ('date_employed', models.DateTimeField(auto_now_add=True, verbose_name='Date Employed')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('profile_pic', models.FileField(blank=True, default='avatar.png', null=True, upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
