# Generated by Django 4.0.6 on 2022-10-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
        ('managements', '0002_employee_leave_allocation_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('director', 'name')},
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
