# Generated by Django 4.0.6 on 2022-10-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
        ('set_salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryattributevaluess', to='set_salary.deductionattributevalue')),
            ],
            options={
                'verbose_name': 'DeductionAttributeValues',
                'verbose_name_plural': 'DeductionAttributeValuess',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_attribute_value', models.ManyToManyField(related_name='DeductionAttributeValue', through='payroll.DeductionAttributeValues', to='set_salary.deductionattributevalue')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='managements.employee')),
            ],
            options={
                'verbose_name': 'EmployeeData',
                'verbose_name_plural': 'EmployeeDatas',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
            },
        ),
        migrations.CreateModel(
            name='PayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.jobrole')),
            ],
            options={
                'verbose_name': 'Pay Grade',
                'verbose_name_plural': 'Pay Grades',
            },
        ),
        migrations.CreateModel(
            name='PayrollManagerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='payroll_manager')),
                ('activated', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Manager Upload',
                'verbose_name_plural': 'Payroll Manager Uploads',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SalaryAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeedata', to='payroll.employeedata')),
                ('salary_attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryattributevaluess', to='set_salary.salaryattributevalue')),
            ],
            options={
                'verbose_name': 'SalaryAttributeValues',
                'verbose_name_plural': 'SalaryAttributeValuess',
                'unique_together': {('salary_attribute_value', 'employee_data')},
            },
        ),
        migrations.CreateModel(
            name='PayrollManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_group', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('basic_pay', models.PositiveIntegerField(default=0)),
                ('housing_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('housing_upfront', models.IntegerField(blank=True, default=0, null=True)),
                ('transport_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('utility_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('passage_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('furniture_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('dressing_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('driver_refund', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('vehicle_refund', models.IntegerField(blank=True, default=0, null=True)),
                ('children_eduction_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('gross_pay', models.IntegerField(blank=True, default=0, null=True)),
                ('paye', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_repayment', models.IntegerField(blank=True, default=0, null=True)),
                ('NHF', models.IntegerField(blank=True, default=0, null=True)),
                ('HMO_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('other_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('status_car_repayment', models.IntegerField(blank=True, default=0, null=True)),
                ('total_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('NET_PAY', models.IntegerField(blank=True, default=0, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='managements.employee')),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_unique_number', to='managements.employee')),
            ],
            options={
                'verbose_name': 'Payroll Manager',
                'verbose_name_plural': 'Payroll Managers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_grade', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.paygrade')),
            ],
            options={
                'verbose_name': 'Pay Group',
                'verbose_name_plural': 'Pay Groups',
            },
        ),
        migrations.AddField(
            model_name='employeedata',
            name='job_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.jobrole'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='pay_grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.paygrade'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='pay_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.paygroup'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='salary_attribute_value',
            field=models.ManyToManyField(related_name='salary_attribute_values', through='payroll.SalaryAttributeValues', to='set_salary.salaryattributevalue'),
        ),
        migrations.AddField(
            model_name='deductionattributevalues',
            name='employee_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_data', to='payroll.employeedata'),
        ),
    ]
