# Generated by Django 3.1.13 on 2022-05-10 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollManagerUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='payroll_manager')),
                ('activated', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Manager Upload',
                'verbose_name_plural': 'Payroll Manager Uploads',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PayrollManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_group', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('basic_pay', models.PositiveIntegerField(default=0)),
                ('housing_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('housing_upfront', models.IntegerField(blank=True, default=0, null=True)),
                ('transport_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('utility_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('passage_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('furniture_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('dressing_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('driver_refund', models.IntegerField(blank=True, default=0, null=True)),
                ('leave_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('vehicle_refund', models.IntegerField(blank=True, default=0, null=True)),
                ('children_eduction_allowance', models.IntegerField(blank=True, default=0, null=True)),
                ('gross_pay', models.IntegerField(blank=True, default=0, null=True)),
                ('paye', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_repayment', models.IntegerField(blank=True, default=0, null=True)),
                ('NHF', models.IntegerField(blank=True, default=0, null=True)),
                ('HMO_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('other_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('status_car_repayment', models.IntegerField(blank=True, default=0, null=True)),
                ('total_deduction', models.IntegerField(blank=True, default=0, null=True)),
                ('NET_PAY', models.IntegerField(blank=True, default=0, null=True)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='managements.employee')),
                ('employee_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_unique_number', to='managements.employee')),
            ],
            options={
                'verbose_name': 'Payroll Manager',
                'verbose_name_plural': 'Payroll Managers',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
