# Generated by Django 4.0.6 on 2022-10-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_deductionattributevalues_director_jobrole_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.jobrole'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='pay_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.paygrade'),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='pay_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.paygroup'),
        ),
    ]
