# Generated by Django 4.0.6 on 2022-10-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'HRM', 'verbose_name_plural': 'HRMs'},
        ),
    ]
